language: c

compiler: gcc

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install libgtk-3-dev

script: 
  - make && make test && make run_test
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
